name: Wetall Manual Scan
on:
  workflow_dispatch: # Permet de cliquer sur "Run Workflow" sur mobile

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install httpx beautifulsoup4

      - name: Run Scan
        run: python wetall_scanner.py

      - name: Save Report to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rapport_scan.md
          git commit -m "MAJ Rapport Scan - $(date)" || exit 0
          git push
          
