name: Crash Test IP GitHub

on:
  workflow_dispatch: # Permet de lancer le test manuellement depuis l'onglet Actions

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          pip install playwright
          playwright install chromium

      - name: Exécution du test
        run: python test_github_ip.py